# Base image
FROM continuumio/miniconda3

# Expose ports
EXPOSE 5000

# Update system
RUN apt update -y
RUN apt upgrade -y
RUN pip install -U pip

# Create and use project directory
WORKDIR /app

# Copy and install requirements
ADD ./spec-file.txt .
RUN conda install -y --file ./spec-file.txt

# Entrypoint
ENTRYPOINT python ./src/app.py
