# Base image
FROM python:3.8-alpine

# Expose ports
EXPOSE 5000

# Update system
RUN apk update
RUN apk upgrade --available
RUN pip install --upgrade pip

# Create and use project directory
RUN mkdir -p /app
WORKDIR /app

# Copy and install requirements
ADD requirements.txt .
RUN pip install -r requirements.txt

# Entrypoint
CMD python src/app.py
